### ISSUE TITLE
Gitea doesn't survive pod recreation

### ISSUE THREAD

**Issue by gs11** [jfelten/gitea-helm-chart#1]
Whenever a pod is restarted Gitea gets in the fresh install mode again and you're redirected to /install and App.ini is subsequently overwritten.

**Comment by gs11** [comment]
So the issue seems to be that app.ini is copied from the Config Map every time.
A quick fix is to copy the data volume app.ini to the config map.

Preferably the data volume app.ini shouldn't be overwritten if it exists?

**Comment by jfelten** [comment]
https://github.com/jfelten/gitea-helm-chart/pull/7

**Comment by jfelten** [comment]
will add you as collaborator so you can review

**Comment by jfelten** [comment]
pr merged - closing
