### ISSUE TITLE
Skip Installation screen 

### ISSUE THREAD

**Issue by DrMegavolt** [jfelten/gitea-helm-chart#13]
Hello, 

The helm chart works great. I'm trying to do step forward and remove installation screen. 

Unless I manually click install, cli and api does not work. 
I need Gitea operation so I can create admin user and generate access token

Do you know how this can be done?
```
# create admin user:
# gitea admin create-user --name=test --password=test --email=test@xx.com --admin

# generate token
# curl -X POST "http://localhost:3000/api/v1/users/test/tokens" -H "accept: application/x-www-form-urlencoded" -H "authorization: Basic dGVzdDp0ZXN0" -F name=ttxxx

# response sha1 is the access key
# {"id":7,"name":"ttxxx","sha1":"2283d9f73439c7b34a644197875e1bf84923a960"}  
```

**Comment by jfelten** [comment]
It should be possible to add this to the init container script: https://github.com/jfelten/gitea-helm-chart/tree/master/templates/init.  I'm not sure what else is necessary to bypass the init screen,  If you figure it out figure it out I would gladly take a PR :).

**Comment by DrMegavolt** [comment]
I think I know. 

2 parts are required: `SECRET_KEY` populated and `INSTALL_LOCK=true`

it seems like SECRET_KEY is set in default config
https://github.com/jfelten/gitea-helm-chart/blob/f62084ea2b783e6d582fab1ce5754f15e946e680/templates/gitea/gitea-config.yaml#L285

but actually it is not. this is how it looks after copying to `/data/gitea/conf/app.ini`
```
INSTALL_LOCK                      = false
; !!CHANGE THIS TO KEEP YOUR USER DATA SAFE!!
#@FDEWREWR&*(
SECRET_KEY                        = !
```
 
After I manually set it to 
```
INSTALL_LOCK                      = true
; !!CHANGE THIS TO KEEP YOUR USER DATA SAFE!!
#@FDEWREWR&*(
SECRET_KEY                        = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
```
it works. 

I'll create a PR to make secret configurable and set it properly

Would you also accept PR that `optionally` generates admin user?

**Comment by jfelten** [comment]
yes - thank you

**Comment by robertgates55** [comment]
@DrMegavolt - did you ever manage to create the admin user directly (or know of a way to create users with a REST API call just using the SECRET_KEY)?

Or is the best way to use the `gitea admin` command from within the pod on first boot?

**Comment by DrMegavolt** [comment]
Ended up with gitea admin command

**Comment by asoltesz** [comment]
I am struggling to make this work.

The Gitea container runs as root and there is no way to customize it via the Helm chart. 

Thus, the "gitea admin" command cannot be executed because Gitea would only accept it from the "git" user.

How can I create the admin user after I have used disableInstaller=false and secretKey ?

**Comment by asoltesz** [comment]
By analizing the entrypoint script, I came up with this one for the admin user (gitea) creation:

exec su-exec git gitea admin create-user --name=gitea --password=gitea --email=test@xx.com --admin --must-change-password=false
