### ISSUE TITLE
Move this into a chart repo

### ISSUE THREAD

**Issue by holmesb** [jfelten/gitea-helm-chart#25]
```
$ helm install --values values.yaml --name gitea --namespace gittea jfelten/gitea
Error: failed to download "jfelten/gitea" (hint: running `helm repo update` may help)
```

Since this isn't in a helm repo, is everyone cloning this git repo and installing from their local file-system?  Seems mature enough to ask for inclusion in the main [https://github.com/helm/charts](https://github.com/helm/charts).  Or am I missing something that will make the install command in the readme work?

**Comment by holmesb** [comment]
I see, it's in jfelton's helm repo:
`helm repo add jfelten https://jfelten.github.io/helm-charts/charts`

Hard work to discover this info tho.  Better to be in https://github.com/helm/charts

**Comment by jfelten** [comment]
I've contributed charts to the main helm registry in the past and wasn't very good at monitoring and maintaining it.  There was at the time also a rather lengthy cumbersome process for reviewing and pushing through changes.  I'm much happier maintaining the chart on my own terms.

That being said - if there are a couple of people who want to take ownership and work with the official helm registry owners I am open to opening a pull request.  My preference would be to contribute the chart to the gitea team if possible though.

**Comment by holmesb** [comment]
Being here is fine if you prefer, but readme's install instructions should direct people how to add the helm repo.  See [PR.](https://github.com/jfelten/gitea-helm-chart/pull/27)
