### ISSUE TITLE
SSH

### ISSUE THREAD

**Issue by holmesb** [jfelten/gitea-helm-chart#26]
Interacting with gitea repos using SSH is easier because using an SSH agent can obviate typing a password.  

Assuming you're using ingress, a `git clone` per the gitea documentation will prompt for a password and fail to authenticate.  I expect this is because nginx is failing to handle TCP (SSH) traffic.

This chart suggests (in NOTES.txt) port-forwarding to the dedicated SSH service.  My question: why not change `service.ssh.serviceType` to LoadBalancer by default instead?  Then no port-forwarding is necessary.

Or an even better solution (that I've not tried), [configure ingress to handle SSH traffic](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/exposing-tcp-udp-services.md) using its proxy-protocol feature.

**Comment by jfelten** [comment]
The chart was written to support bare metal, which uses NodePorts.  I've been out of the loop for a bit and don't know if there is a good way to set up load balancers on bare metal now.  If you know of an easy way to set up a LoadBalancer on bare metal I'd be willing to try it out.

If there is a way to enhance the config to accept both NodePorts and Load Balancers I would happily accept a PR.

**Comment by jfelten** [comment]
merged your PR - can you verify if fixed and close this?
