### ISSUE TITLE
Possible regression for 'do not overwrite app.ini if it exists in persistent storage'

### ISSUE THREAD

**Issue by paulgrahek** [jfelten/gitea-helm-chart#38]
Using existing app.ini in the PV storage added in #7 appears to have been removed in the 1.6.1 upgrade in #15. The init container ran during ```helm install``` or ```helm upgrade``` now overwrites the existing app.ini file.

**Comment by jfelten** [comment]
I tested this recently on 1.12 and it seems to work - please reopen if you encouter this again.
