### ISSUE TITLE
[Feature]Separate Postgres/Memcached/Gitea

### ISSUE THREAD

**Issue by caryyu** [jfelten/gitea-helm-chart#41]
Due to Kubernetes Pod is a fundamental unit for orchestrating inside the cluster, which sometimes, we only want Gitea to be orchestrated instead of including Postgres/Memcached yet, plus, I think you don't need to have Postgres/Memcached in your repo since Helm supports the dependency management with a file `requirements.txt` in place to let you bind all the stuff together..

**Comment by jfelten** [comment]
This was a decision I made when I wrote the chart. At that point the dependency management was flaky and the dependent charts like postgres were changing rapidly causing breakages.  This was an attempt to add some robustness. 

It makes sense to revisit this now, and is probably a good idea. I am not opposde to this if somebody wants to change.

**Comment by caryyu** [comment]
@jfelten Due to the consideration of the compatibility extending from your chart, I rewrote/recreated the whole chart for myself: https://github.com/caryyu/gitea-helm-chart
