### ISSUE TITLE
Custom values in the README create a 503 error

### ISSUE THREAD

**Issue by huats** [jfelten/gitea-helm-chart#54]
The proposed custom values that are in the README creates a 503 error when trying to reach the application. That 503 error is created by the ingress due to the annotation
nginx.ingress.kubernetes.io/auth-type: basic

Is there a reason to keep it ? or can we simply delete it in order to help the maximum number of people that try to use that helm chart ?

**Comment by jfelten** [comment]
It can be removed. Feel free to do a PR or I will when set up CIC over hte next week or 2.

**Comment by huats** [comment]
Fixed in #55

**Comment by huats** [comment]
Fixed in #55  that is merged
