### ISSUE TITLE
gitea chart not available anymore

### ISSUE THREAD

**Issue by huats** [jfelten/gitea-helm-chart#61]
I think since the 1.12.2 update in master, the gitea chart is not available anymore. 
On a fresh install
```
$ helm repo add keyporttech https://keyporttech.github.io/helm-charts/
$ helm search repo
NAME              	CHART VERSION	APP VERSION	DESCRIPTION                                 
keyporttech/statsd	0.1.4        	v0.8.6     	a simple chart to deploy statsd to a cluster
$ helm search repo gitea
No results found
```

**Comment by jfelten** [comment]
I have identified the issue and am working on a solution.

**Comment by jfelten** [comment]
https://github.com/jfelten/gitea-helm-chart/pull/64 - should now publish properly on PR merge

**Comment by jfelten** [comment]
published version should be up to date - closing
