### ISSUE TITLE
Missing External DB Secret

### ISSUE THREAD

**Issue by kevinlmadison** [jfelten/gitea-helm-chart#76]
I'm seeing this error when describing the gitea pod.
```
 Warning  Failed     6m48s (x12 over 8m49s)  kubelet            Error: secret "gitea-externaldb" not found
```
The pod is stuck here:
```
pod/gitea-gitea-64b56bbcd8-v2r67                                   0/2     Init:CreateContainerConfigError   0
```

I'm trying to connect to an external postgres db. Am I missing something obvious?

Thank You!

**Comment by jfelten** [comment]
make sure .Values.useInPodPostgres is false

**Comment by kevinlmadison** [comment]
ah that worked thank you! I have another issue now but I'll create a new issue for it!
