### ISSUE TITLE
Uploaded avatars lost on pod restart or physical host restart

### ISSUE THREAD

**Issue by nodesocket** [jfelten/gitea-helm-chart#80]
When the underlying physical server running Gitea is restarted and the Kubernetes pods come back online, all of my custom uploaded avatars are lost. Is there a way to store the custom uploaded avatars in a persistent volume?

Running `helm v2` and an older version of this chart because of that fact. Perhaps this is fixed in the latest version, but looking to port that change into my old v2 chart.

```
version: 1.9.3
appVersion: 1.12.5
```

**Comment by jfelten** [comment]
This has been something that I noticed a while back and you are the first person to bring it up. - will triage. We are only supporting helm V3 now - I'll update the README.

**Comment by jfelten** [comment]
Generated a PR to fix this. Will leave it up for a day in case anyone wants to review and merge if no reviews.

Note for current installations the app.ini will need to be regenerated in order for these changes to be applied

One way to do so is:

```
kubectl exec -it <ACTIVE_POD> -n <DEPLOYED_NAMESPACE> gitea --bash
cd /data//gitea/conf/app.ini
mv app.ini app.ini_old
```

the redeploy to the newer version of the chart. The installer will come up in a webpage and will regenerate the app.ini on saving.

**Comment by nodesocket** [comment]
@jfelten so if I just set `STATIC_ROOT_PATH = data/static` in my `gitea/gitea-config.yaml` and then run a`helm upgrade` will that store avatars in persistent volume then?

Also, why did you change nearly all paths in config to start with a `/` in that PR?
